#!/usr/bin/env bash
#
# A wizard — walks a human through a manual procedure step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library — delightful, consistent UX. Identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear — wipe the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" — opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later — it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" — clear the screen, then announce a stage and show progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." — a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." — a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL — open in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser — visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser — visit it manually: $url"
}

# pause "msg" — wait for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" — y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY — current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" — read a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" — like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE — upsert KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE — set a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name — gh not ready; set it later"
}

# set_var NAME VALUE — set a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name — gh not ready; set it later"
}

# finish — clear, then a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES — author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=6

# Always write to the project's .env, regardless of which folder this script was launched from.
ENV_FILE="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)/.env"

banner "Gmail credentials for regular report emails"

# ── Stage 1: create/select the GCP project ─────────────────────────────────
stage "Google Cloud project"
say "The regular report needs a Google Cloud project to hold the Gmail API access."
note "If you already created a project for Google Drive access, you can reuse the same one —"
note "just make sure it's selected below."
open_url "https://console.cloud.google.com/projectcreate"
step "Name it something like 'kpi-tracker' and click Create (or select your existing one)."
step "Make sure it's selected in the project dropdown at the top of the page."
pause "Done? Press Enter to continue."

# ── Stage 2: enable the Gmail API ───────────────────────────────────────────
stage "Enable the Gmail API"
say "This turns on Gmail access for the project you just selected."
open_url "https://console.cloud.google.com/apis/library/gmail.googleapis.com"
step "Click 'Enable' (if it already says 'Manage', it's already on — skip ahead)."
pause "Done? Press Enter to continue."

# ── Stage 3: OAuth consent screen ───────────────────────────────────────────
stage "OAuth consent screen"
say "This is where you tell Google who's allowed to use this app while it's unpublished."
note "If you already set this up for Google Drive, you just need to add the Gmail send scope."
open_url "https://console.cloud.google.com/apis/credentials/consent"
step "User type: External. App name: 'KPI Tracker'. User support email + developer contact: your own email."
step "On the Scopes step, add the scope: https://www.googleapis.com/auth/gmail.send"
step "On the Test users step, add your own Google account email as a test user."
step "Save through to the end (you don't need to submit for verification)."
warn "Unverified apps: Google may cap refresh tokens at 7 days for test users. If your"
warn "token stops working later, come back here and click 'Publish App' — you'll still"
warn "see an 'unverified app' warning when you sign in, which is expected and safe to click through for your own app."
pause "Done? Press Enter to continue."

# ── Stage 4: OAuth client ID ────────────────────────────────────────────────
stage "OAuth client ID"
say "This is the app's identity — the ID/secret pair the report sender uses to ask for access."
note "You can reuse the same OAuth client you created for Google Drive, or make a new one just for Gmail."
open_url "https://console.cloud.google.com/apis/credentials"
step "Click '+ Create Credentials' → 'OAuth client ID' (or reuse an existing one)."
step "Application type: Web application. Name: 'KPI Tracker'."
step "Under 'Authorized redirect URIs', click '+ Add URI' and paste exactly:"
note "    https://developers.google.com/oauthplayground"
step "Click Create. A popup shows the Client ID and Client Secret — keep this tab open, you'll need both now and again in the next stage."
ask GOOGLE_GMAIL_CLIENT_ID "Paste the Client ID:"
ask GOOGLE_GMAIL_CLIENT_SECRET "Paste the Client Secret:"
write_env GOOGLE_GMAIL_CLIENT_ID "$GOOGLE_GMAIL_CLIENT_ID"
write_env GOOGLE_GMAIL_CLIENT_SECRET "$GOOGLE_GMAIL_CLIENT_SECRET"

# ── Stage 5: refresh token via OAuth Playground ─────────────────────────────
stage "Refresh token"
say "The refresh token is what lets the report sender send mail without you"
say "signing in again every time. We'll get it from Google's own OAuth Playground."
open_url "https://developers.google.com/oauthplayground/"
step "Click the gear icon (top right) → check 'Use your own OAuth credentials'."
step "Paste the Client ID and Client Secret from the previous stage → close settings."
step "In the left panel, find the box labeled 'Input your own scopes' and paste:"
note "    https://www.googleapis.com/auth/gmail.send"
step "Click 'Authorize APIs', sign in with the same Google account you added as a test user."
step "You'll likely see 'Google hasn't verified this app' — click Advanced → 'Go to KPI Tracker (unsafe)' → Allow. This is expected for your own unpublished app."
step "You're redirected back to the Playground with an authorization code in Step 1."
step "Click 'Exchange authorization code for tokens' (Step 2) — a 'Refresh token' field appears."
ask GOOGLE_GMAIL_REFRESH_TOKEN "Paste the refresh token:"
write_env GOOGLE_GMAIL_REFRESH_TOKEN "$GOOGLE_GMAIL_REFRESH_TOKEN"

# ── Stage 6: push to GitHub so the scheduled workflow can send even when your laptop is off ─
stage "GitHub Actions secrets"
say "The regular report is sent by a scheduled GitHub Actions workflow (.github/workflows/regular-report.yml),"
say "which runs in the cloud and needs its own copy of these values as repo secrets/variables."
ask REPORT_RECIPIENT_EMAIL "Email address the reports should be sent to:"
ask DASHBOARD_URL "관리 화면 URL (leave blank to use the placeholder for now):"
write_env REPORT_RECIPIENT_EMAIL "$REPORT_RECIPIENT_EMAIL"
[[ -n "$DASHBOARD_URL" ]] && write_env DASHBOARD_URL "$DASHBOARD_URL"
set_secret GOOGLE_GMAIL_CLIENT_ID "$GOOGLE_GMAIL_CLIENT_ID"
set_secret GOOGLE_GMAIL_CLIENT_SECRET "$GOOGLE_GMAIL_CLIENT_SECRET"
set_secret GOOGLE_GMAIL_REFRESH_TOKEN "$GOOGLE_GMAIL_REFRESH_TOKEN"
set_secret REPORT_RECIPIENT_EMAIL "$REPORT_RECIPIENT_EMAIL"
[[ -n "$DASHBOARD_URL" ]] && set_var DASHBOARD_URL "$DASHBOARD_URL"
note "GOOGLE_DRIVE_* secrets (from the Drive setup wizard) also need to be set on GitHub for the"
note "workflow to read your KPI data — run scripts/setup-google-drive-credentials.sh's GitHub push"
note "manually if it wasn't already: gh secret set GOOGLE_DRIVE_CLIENT_ID < .env, etc."
# ──────────────────────────────────────────────────────────────────────────

finish
